// src/components/Chat.tsx
import { useState, useEffect } from 'react'

export default function Chat({ updatePreview }: { updatePreview: any }) {
  type ChatMessage = {
    role: string
    content: string
    error?: string
  }

  const [newMessage, setNewMessage] = useState<string>('')
  const [messages, setMessages] = useState<ChatMessage[]>([
    { role: 'system', content: 'Hello! How can I help you today?' },
  ])
  const [errorMessage, setErrorMessage] = useState<string>('')
  const [isLoading, setIsLoading] = useState<boolean>(false)

  function handleInputKeyPress(event: React.KeyboardEvent<HTMLInputElement>) {
    if (event.key === 'Enter') {
      if (newMessage.trim() === '') {
        setErrorMessage('Please enter a message')
        setTimeout(() => setErrorMessage(''), 1500)
        return
      } else {
        sendMessage()
      }
    }
  }

  async function sendMessage() {
    if (newMessage.trim() === '') {
      setErrorMessage('Please enter a message')
      setTimeout(() => setErrorMessage(''), 1500)
      return
    }

    try {
      const userMessage: ChatMessage = {
        role: 'user',
        content: newMessage,
      }

      setTimeout(() => setIsLoading(true), 500, 0)

      setMessages((prevMessages) => [userMessage, ...prevMessages])

      const response = await fetch('/api/chat-gpt', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message: newMessage }),
      })

      if (response.ok) {
        setNewMessage('')

        const responseData = await response.json()
        const botResponse: ChatMessage = {
          role: 'bot',
          content: responseData.message,
        }

        setMessages((prevMessages) => [botResponse, ...prevMessages])
        updatePreview(responseData.message)
      } else {
        const errorData = await response.json()
        const errorMessage = errorData.error || 'Unknown error'

        const botResponse: ChatMessage = {
          role: 'bot',
          content: errorMessage,
          error: errorMessage,
        }

        setMessages((prevMessages) => [botResponse, ...prevMessages])
      }
    } catch (error: any) {
      const errorMessage = "Sorry, I'm struggling with that request"

      const botResponse: ChatMessage = {
        role: 'bot',
        content: errorMessage,
        error: errorMessage,
      }

      setMessages((prevMessages) => [botResponse, ...prevMessages])
    } finally {
      setIsLoading(false)
    }
  }

  useEffect(() => {
    const chatContainer = document.querySelector('.chat-messages')
    if (chatContainer) {
      chatContainer.scrollTop = 0
    }
  }, [messages])

  return (
    <div className="chat-wrapper">
      <div>
        <h1>Chat</h1>
        <div className="chat-container">
          <div className="chat-messages">
            {isLoading && (
              <div className="chat-message bot-message">Loading...</div>
            )}
            {messages.map((message, index) => (
              <div
                key={index}
                className={`chat-message ${
                  message.role === 'user' ? 'user-message' : 'bot-message'
                }`}
              >
                {message.content}
              </div>
            ))}
          </div>
        </div>
      </div>
      <div className="input-container">
        <p>{errorMessage}</p>
        <input
          type="text"
          placeholder="Type your message..."
          value={newMessage}
          onChange={(e) => setNewMessage(e.target.value)}
          onKeyUp={handleInputKeyPress}
          required
        />
        <button onClick={sendMessage}>Send</button>
      </div>
    </div>
  )
}

// components/Chat.vue
<template>
  <div style="display: flex; flex-direction: column; height: 100%">
    <h1 style="text-align: center">Chat</h1>

    <div
      style="
        flex-grow: 1;
        overflow-y: auto;
        border: 1px solid #ccc;
        padding: 10px;
      "
      ref="scrollableContent"
    >
      <div
        v-for="message in messages"
        :key="message"
        style="border: 1px solid #ccc; padding: 10px"
      >
        {{ message }}
      </div>
    </div>

    <div
      style="
        display: flex;
        align-items: center;
        padding: 10px;
        border-top: 1px solid #ccc;
      "
    >
      <input
        v-model="newMessage"
        style="flex-grow: 1; padding: 5px; margin-right: 10px"
        placeholder="Type your message..."
      />
      <button
        @click="sendMessage"
        style="
          padding: 5px 10px;
          background-color: #007bff;
          color: #fff;
          border: none;
          cursor: pointer;
        "
      >
        Send
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ChatMessage } from '~/types/ChatMessage'

const messages = ref<string[]>([])
const newMessage = ref('')
const botMessage = ref('')

async function sendMessage() {
  if (newMessage.value.trim() !== '') {
    const userMessage: ChatMessage = {
      role: 'user',
      content: newMessage.value,
    }

    messages.value.push(userMessage.content)

    newMessage.value = ''

    const { data } = await useFetch('/api/chatGPT', {
      method: 'POST',
      body: JSON.stringify(userMessage.content),
    })

    botMessage.value = data.value || 'Sorry, I am struggling with that request'

    messages.value.push(botMessage.value)
  }
}
</script>
